import { theme } from '@/theme';
import React from 'react';

const RaceDecoration = () => {
    return (
        <svg
            width='100%'
            height='100'
            xmlns='http://www.w3.org/2000/svg'
            viewBox='0 0 1000 100'
        >
            <rect
                x='50'
                y='20'
                width='900'
                height='60'
                rx='30'
                ry='30'
                fill='#FFFFFF'
                stroke='none'
            />
            <rect
                x='50'
                y='20'
                width='800'
                height='60'
                rx='30'
                ry='30'
                fill={theme.palette.primary.main}
                stroke='none'
            />
            <line
                x1='150'
                y1='20'
                x2='150'
                y2='80'
                stroke='#FFFFFF'
                strokeWidth='2'
            />
            <line
                x1='250'
                y1='20'
                x2='250'
                y2='80'
                stroke='#FFFFFF'
                strokeWidth='2'
            />
            <line
                x1='350'
                y1='20'
                x2='350'
                y2='80'
                stroke='#FFFFFF'
                strokeWidth='2'
            />
            <line
                x1='450'
                y1='20'
                x2='450'
                y2='80'
                stroke='#FFFFFF'
                strokeWidth='2'
            />
            <line
                x1='550'
                y1='20'
                x2='550'
                y2='80'
                stroke='#FFFFFF'
                strokeWidth='2'
            />
            <line
                x1='650'
                y1='20'
                x2='650'
                y2='80'
                stroke='#FFFFFF'
                strokeWidth='2'
            />
            <line
                x1='750'
                y1='20'
                x2='750'
                y2='80'
                stroke='#FFFFFF'
                strokeWidth='2'
            />
            <line
                x1='850'
                y1='20'
                x2='850'
                y2='80'
                stroke='#FFFFFF'
                strokeWidth='2'
            />
            <circle cx='50' cy='50' r='25' fill='#000000' />
            <text
                x='50'
                y='55'
                font-family='Arial'
                font-size='20'
                fill='#FFFFFF'
                text-anchor='middle'
                alignment-baseline='middle'
            >
                01
            </text>
            <circle cx='850' cy='50' r='25' fill='#000000' />
            <text
                x='850'
                y='55'
                font-family='Arial'
                font-size='20'
                fill='#FFFFFF'
                text-anchor='middle'
                alignment-baseline='middle'
            >
                13
            </text>
            <text
                x='920'
                y='55'
                font-family='Arial'
                font-size='20'
                fill='#000000'
                text-anchor='middle'
                alignment-baseline='middle'
            >
                🏁
            </text>
        </svg>
    );
};

export default RaceDecoration;
